- name: Create New User
  hosts: all
  become: true
  gather_facts: false
  remote_user: coding
  vars:
    username: esiee
    userpass: esiee
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
        append: yes

    - name: Deploy SSH Public Key
      authorized_key: user=esiee
                    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                    state=present
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    - name: Create html directory
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: esiee
        mode: 0777